"use strict";
const canvas=document.querySelector('#arena'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const $=s=>document.querySelector(s);const keys=new Set();const mouse={x:W/2,y:H/2,down:false};
const upgrades=[['锋利墨刃','攻击伤害 +8','damage'],['残影步','移动速度 +18%','speed'],['黑曜心','最大生命 +25，并回复','hp'],['连斩回响','攻击冷却 -20%','cooldown']];
let game={mode:'start',room:1,wave:1,score:0,kills:0,shake:0,spawnTimer:0,attackTimer:0,particles:[],slashes:[],enemies:[],player:{x:W/2,y:H/2,hp:100,maxHp:100,xp:0,next:30,damage:22,speed:190,cooldown:.34,r:16},door:false};
function reset(){game={...game,mode:'play',room:1,wave:1,score:0,kills:0,spawnTimer:0,attackTimer:0,particles:[],slashes:[],enemies:[],door:false,player:{x:W/2,y:H/2,hp:100,maxHp:100,xp:0,next:30,damage:22,speed:190,cooldown:.34,r:16}};spawnWave();log('第 1 房间：黑潮开始涌入。');updateUI()}
function spawnWave(){game.enemies=[];const count=4+game.room*2;for(let i=0;i<count;i++){const side=i%4;let x=side===0?30:side===1?W-30:Math.random()*W,y=side===2?30:side===3?H-30:Math.random()*H;game.enemies.push({x,y,hp:30+game.room*6,max:30+game.room*6,r:side%2?15:19,type:side%2?'bat':'slime',speed:side%2?72:48,hit:0,atk:0})}}
function log(t){$('#combatLog').textContent=t}function addParticle(x,y,color,n=8){for(let i=0;i<n;i++)game.particles.push({x,y,vx:(Math.random()-.5)*120,vy:(Math.random()-.5)*120,life:.45,color})}
function attack(){if(game.mode!=='play'||game.attackTimer>0)return;game.attackTimer=game.player.cooldown;const p=game.player,ang=Math.atan2(mouse.y-p.y,mouse.x-p.x);game.slashes.push({x:p.x,y:p.y,a:ang,life:.18});addParticle(p.x+Math.cos(ang)*28,p.y+Math.sin(ang)*28,'#d2ff00',5);for(const e of game.enemies){const dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy),da=Math.abs(Math.atan2(Math.sin(Math.atan2(dy,dx)-ang),Math.cos(Math.atan2(dy,dx)-ang)));if(d<82&&da<.75){e.hp-=p.damage;e.hit=.12;addParticle(e.x,e.y,e.type==='bat'?'#b565ff':'#7bff6a',12);if(e.hp<=0){game.kills++;game.score+=100*game.room;gainXp(10);log(`击倒 ${e.type==='bat'?'噪蝠':'墨泥'}，继续推进。`)}}}}
function gainXp(n){game.player.xp+=n;if(game.player.xp>=game.player.next){game.player.xp-=game.player.next;game.player.next=Math.floor(game.player.next*1.35);game.mode='level';show('#levelCard');renderChoices();log('黑墨沸腾：选择一项强化。')}}
function renderChoices(){const el=$('#upgradeChoices');el.innerHTML='';upgrades.sort(()=>Math.random()-.5).slice(0,3).forEach(u=>{const b=document.createElement('button');b.className='upgrade';b.innerHTML=`<strong>${u[0]}</strong><small>${u[1]}</small>`;b.onclick=()=>{const p=game.player;if(u[2]==='damage')p.damage+=8;if(u[2]==='speed')p.speed*=1.18;if(u[2]==='hp'){p.maxHp+=25;p.hp=p.maxHp}if(u[2]==='cooldown')p.cooldown*=.8;hide('#levelCard');game.mode='play';if(!game.enemies.length)spawnWave();log(`强化完成：${u[0]}`);updateUI()};el.appendChild(b)})}
function update(dt){const p=game.player;if(game.mode!=='play')return;game.attackTimer=Math.max(0,game.attackTimer-dt);let vx=(keys.has('d')?1:0)-(keys.has('a')?1:0),vy=(keys.has('s')?1:0)-(keys.has('w')?1:0),len=Math.hypot(vx,vy)||1;p.x=Math.max(28,Math.min(W-28,p.x+vx/len*p.speed*dt));p.y=Math.max(28,Math.min(H-28,p.y+vy/len*p.speed*dt));for(const e of game.enemies){e.hit=Math.max(0,e.hit-dt);e.atk-=dt;const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(d>e.r+p.r+4){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}else if(e.atk<=0){e.atk=e.type==='bat'?1.1:1.5;p.hp-=e.type==='bat'?5:8;game.shake=.12;addParticle(p.x,p.y,'#ff2b8b',7);log('受击！别让它们贴脸。')}}game.enemies=game.enemies.filter(e=>e.hp>0);for(const q of game.particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt}game.particles=game.particles.filter(q=>q.life>0);game.slashes.forEach(s=>s.life-=dt);game.slashes=game.slashes.filter(s=>s.life>0);if(p.hp<=0){game.mode='over';show('#gameOverCard');$('#finalScore').textContent=`击倒 ${game.kills} 个敌人 · 得分 ${game.score}`;log('黑潮吞没了你。')}if(!game.enemies.length){game.room++;game.score+=500;game.mode='level';show('#levelCard');renderChoices();$('#objectiveTitle').textContent='房间清空';$('#objectiveText').textContent=`第 ${game.room-1} 房间完成，选择强化后开门`}}
function draw(){ctx.save();if(game.shake){ctx.translate((Math.random()-.5)*6,(Math.random()-.5)*6);game.shake=Math.max(0,game.shake-.016)}ctx.fillStyle='#101820';ctx.fillRect(0,0,W,H);for(let y=0;y<H;y+=32)for(let x=0;x<W;x+=32){ctx.strokeStyle=(x+y)%64?'#1a2934':'#203341';ctx.strokeRect(x,y,32,32)}ctx.fillStyle='#2439ff';ctx.globalAlpha=.25;ctx.fillRect(50,80,190,4);ctx.fillRect(700,420,180,4);ctx.globalAlpha=1;for(const e of game.enemies){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.type==='bat'?'#b565ff':'#7bff6a';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=12;ctx.beginPath();if(e.type==='bat'){ctx.moveTo(-18,5);ctx.lineTo(-5,-14);ctx.lineTo(0,-7);ctx.lineTo(5,-14);ctx.lineTo(18,5);ctx.lineTo(5,1);ctx.lineTo(0,13);ctx.lineTo(-5,1)}else{ctx.arc(0,0,e.r,0,7)}ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#080a0d';ctx.fillRect(-7,-3,4,4);ctx.fillRect(4,-3,4,4);ctx.restore()}const p=game.player;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(Math.atan2(mouse.y-p.y,mouse.x-p.x));ctx.fillStyle='#d2ff00';ctx.shadowColor='#d2ff00';ctx.shadowBlur=14;ctx.beginPath();ctx.moveTo(20,0);ctx.lineTo(-10,-15);ctx.lineTo(-17,0);ctx.lineTo(-10,15);ctx.closePath();ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#080a0d';ctx.fillRect(-5,-4,5,5);ctx.fillStyle='#ff2b8b';ctx.fillRect(10,-3,27,6);ctx.restore();for(const s of game.slashes){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(s.a);ctx.strokeStyle='#fff';ctx.lineWidth=7;ctx.globalAlpha=s.life/.18;ctx.beginPath();ctx.arc(0,0,62,-.72,.72);ctx.stroke();ctx.restore()}for(const q of game.particles){ctx.globalAlpha=Math.max(0,q.life/.45);ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,4,4)}ctx.restore()}
function updateUI(){$('#hpText').textContent=`${Math.max(0,Math.ceil(game.player.hp))} / ${game.player.maxHp}`;$('#hpBar').style.width=`${Math.max(0,game.player.hp/game.player.maxHp*100)}%`;$(`#xpText`).textContent=`${game.player.xp} / ${game.player.next}`;$('#xpBar').style.width=`${game.player.xp/game.player.next*100}%`;$('#roomLabel').textContent=`ROOM ${String(Math.max(1,game.room)).padStart(2,'0')}`;$('#waveLabel').textContent=`WAVE ${String(game.wave).padStart(2,'0')}`;$('#scoreText').textContent=`SCORE ${String(game.score).padStart(5,'0')}`;$('#slimeCount').textContent=game.enemies.filter(e=>e.type==='slime').length;$('#batCount').textContent=game.enemies.filter(e=>e.type==='bat').length;document.querySelectorAll('.map-cell').forEach((c,i)=>{c.className='map-cell '+(i<game.room-1?'done':i===game.room-1?'current':'locked')})}
function show(s){$(s).classList.remove('hidden')}function hide(s){$(s).classList.add('hidden')}function loop(t){const dt=Math.min(.033,(t-(loop.last||t))/1000);loop.last=t;update(dt);draw();updateUI();requestAnimationFrame(loop)}
for(let i=0;i<15;i++){const c=document.createElement('i');c.className='map-cell locked';$('#mapGrid').appendChild(c)}addEventListener('keydown',e=>{keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='p')togglePause()});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*W/r.width;mouse.y=(e.clientY-r.top)*H/r.height});canvas.addEventListener('mousedown',()=>{mouse.down=true;attack()});addEventListener('mouseup',()=>mouse.down=false);$('#startButton').onclick=()=>{hide('#startCard');reset()};$('#restartButton').onclick=()=>{hide('#gameOverCard');reset()};$('#pauseButton').onclick=togglePause;function togglePause(){if(game.mode==='play'){game.mode='pause';show('#pauseCard')}else if(game.mode==='pause'){game.mode='play';hide('#pauseCard')}}requestAnimationFrame(loop);
